### ISSUE TITLE
Can't go back to game from upper menu (Nvidia Shield)

### ISSUE THREAD

**Issue by colibris79** [Bankaimaster999/Dolphin-MMJR#14]
Hi, 
I have been using Dolphin-MMJR in my cellphone without any issues, it works great. I was trying it in my Nvidia Shield and it seems to work better than the official Dolphin app. The only problem is that when I open the upper menu I just can't go back to the game. I know Dolphin-MMJR is designed to be used in smartphones and not in Android TV but I was wondering if I am just missing something. I'd really would love to use it also in my Nvidia Shield.
Thanks

**Comment by Bankaimaster999** [comment]
I'm sorry to hear that ...
https://www.reddit.com/r/EmulationOnAndroid/comments/qbtjv9/thanks_for_supporting_mmjrmmjr2_so_far_but/
