### ISSUE TITLE
How do I compile this source?

### ISSUE THREAD

**Issue by PRMan99** [Bankaimaster999/Dolphin-MMJR#18]
I'm a Software Architect but I've never compiled a mixed Android app like this before with C++ and Java.

Can you get me started?

**Comment by Bankaimaster999** [comment]
download the zip file and run the build.gradle from the Source/Android folder in android studio and let it compile.

**Comment by PRMan99** [comment]
OK, I downloaded the NDK and other stuff and got it to finish compiling by running build.gradle, but I don't see a dolphin .apk anywhere.

Anything I am missing?
