### ISSUE TITLE
VPS values on the screen

### ISSUE THREAD

**Issue by ivan89el** [Bankaimaster999/Dolphin-MMJR#19]
In my opinion, this is important debugging information that is not in the official version, but is in the old mmj.
https://sun9-67.userapi.com/impg/I0w2P-PWk62mYfRXoTTMXFdzQBGjPCD-YJ_Bgg/mtvvFrwMhOU.jpg?size=1280x720&quality=96&sign=6b44294f0804415afa6f4ad267e77e42&type=album

**Comment by Bankaimaster999** [comment]
This is not an issue ... and also the wrong place to submit this ...
