### ISSUE TITLE
No SD card support for Android 12

### ISSUE THREAD

**Issue by ibin7777** [Bankaimaster999/Dolphin-MMJR#20]
Android 12 uses a new way to Grant storage permission, 
Within the ape I can only access to the internal storage
On dolphin MMJR2 this issue does not appear since it uses the the system storage selector
Could you maybe consider adding that functions onto the MMJR as well?

**Comment by Bankaimaster999** [comment]
Not really working on the builds ... only updating MMJR2 on a whim
