### ISSUE TITLE
Comment.

### ISSUE THREAD

**Issue by persianstryx** [Bankaimaster999/Dolphin-MMJR#22]
..MMJR is really where it's at. I've been testing every single dolphin version and variant there is out there but they each fall short in one way or the other. Your MMJR version truly is perfect...it's the perfect balance between performance and slight accessibility. Hence the meaning of perfection.. Earlier today I was convinced the Mod version 17035 variant was the most reliable due to the fact that it performed well and it had the in game option to choose controller (which very few have and it's very useful) only three have that option. Yours, Gamer64's and the 17035 variant..(Not to mention the official versions of course.) But in between the fact that the version 17035 quite possibly had malware and that it portrayed fake resolution options it wasn't exactly realiable. Not to mention the fact that it didn't come with a cheat code manager (which was very inconvenient having to burn my lashes looking through codes for the one i was looking for to copy and paste it somewhere else) it wasn't without it's merits, but it performed well, and that's why I stuck with it. I recently started comparing it's specs with my all time favorite version of dolphin (MMJR). As it turns out mmjr not only performs better than this variant but it's safe, reliable, comes with the in game option to choose controllers. Shows more in-depth true resolution options and it comes with it's very own cheat code manager. I was sold. The only thing that would make this app truly great would be the texture options added to it. In the emulation world where performance is king. Dolphin MMJR reigns.
Also the main reason I stuck with the 17035 variant was because it was able to perform with any game, and I mean EVERY game. Recently MMJR2 and all the official versions haven't quite been able to do that. I've only been able to successfully play only three of my games on it. Which I thought was the same case for it's predecessor mmjr but thankfully it was not the case.

**Comment by Bankaimaster999** [comment]
https://github.com/Bankaimaster999/Dolphin-MMJR/releases/tag/1.0-11465

Not taking any further requests with this build
