### ISSUE TITLE
Can't use actual analog triggers from a controller in Revamp (GameCube)

### ISSUE THREAD

**Issue by SoumyBhow** [Bankaimaster999/Dolphin-MMJR#26]
I attempted to play Super Mario Sunshine with the analog triggers on my controller. I mapped the L and R triggers of my controller to L and R triggers in the input menu respectively. In Dolphin Official, mapping my controller this way would let me spray while running with a half press and spray while standing still with a full press. On revamp, it only registers as a full press with no half press in between. I know I could just map my bumpers to the L and R analog but i was hoping I could just use my analog triggers seeing that it's possible in official dolphin. Would you consider fixing this in a future update perhaps? Thank you for your time.

**Comment by sspacelynx** [comment]
The way analog triggers work in MMJR 2.0 is the same as MMJR 1.0, so mapping bumpers to L/R would make them behave as digital buttons, while if you want them to have full analog range, you should use L/R analog. See it this way, both mappings will press the same buttons, just in a different way. You don't need to map all four, just map the two you want.

**Comment by SoumyBhow** [comment]
I see. Mapping my triggers to both regular and analog triggers solved the issue. Thanks!
