### ISSUE TITLE
Use this to fix the display cutout issue

### ISSUE THREAD

**Issue by Jokkaj** [Bankaimaster999/Dolphin-MMJR#29]
put this "styles.xml" file inside /res/values-v28 to fix the ugly black bar https://bugs.dolphin-emu.org/attachments/8316/BlackBar.jpg

download -> [styles.zip](https://github.com/Bankaimaster999/Dolphin-MMJR/files/6626320/styles.zip)

Sorry, I don't know how to create pull requests :\

**Comment by Nejsplitter** [comment]
@Jokkaj does this work for you ? im not sure wher to put that styles xml on my android
