### ISSUE TITLE
Random crashes in various games

### ISSUE THREAD

**Issue by RaduNastase** [Bankaimaster999/Dolphin-MMJR#3]
In Donkey Kong Returns amd Viewtiful Joe i get random freeze followed by crash to gui. 
It happends at random times, sometimes after 5 minutes, sometimes after 30.

OnePlus 7 Android 9

I don't have issues like these in any ither emus 🙏

**Comment by Bankaimaster999** [comment]
This doesn't really help me figure anything out though ...
No logs + I cannot recreate the issue for testing; plus I had users/testers run those same games on Android 10 and 9 and they reported no crashing.
So not sure if its the emulator or your devices settings or just overall settings ....
