### ISSUE TITLE
Have trouble on enabling the ir pointer

### ISSUE THREAD

**Issue by Lemoncak3** [Bankaimaster999/Dolphin-MMJR#31]
Hello can you help, whenever playing fragile dreams my pointer keep missing in gameplay and only appear when in campfire, start game and such. Can you make an enabler to enable and hide ir pointer like what you did in mmjr before? Cause i like your new dolphin revamp now and hope you consider this since bit hard to play games with or pointer requirement

what i mean in mmjr is this button
![IMG-20210611-WA0000](https://user-images.githubusercontent.com/67026697/121632005-60125f80-caaa-11eb-9cea-af4ca97b141b.jpg)

Because in new mmjr my pointer won't appear even when i am looking for object
![Screenshot_20210611-114457](https://user-images.githubusercontent.com/67026697/121632098-9059fe00-caaa-11eb-8bc7-07a04a738034.png)

But in campfire when i don't need to move my character, the ir pointer appear and can be moved using joystick
![Screenshot_20210611-114627](https://user-images.githubusercontent.com/67026697/121632200-c4352380-caaa-11eb-8865-65abe3db542a.png)

Have tried all setting in motion controls but can't find how to enable ir pointer

**Comment by Bankaimaster999** [comment]
That button doesn't enable the IR point .... is actually for Upright Toggle of the pointer.

Also this is not an issue but a request so its in the wrong place and invalid
