### ISSUE TITLE
MMJR2 doesn't locate/ startup games correctly 

### ISSUE THREAD

**Issue by Vulcas** [Bankaimaster999/Dolphin-MMJR#32]
Basically this video explains it: I installed the latest version of MMJR2 by Lumince and well, yeah basically this:
https://user-images.githubusercontent.com/95429848/157349922-46adb528-93d5-4f43-b1ef-5ba75c8d2ca6.mp4

Then when trying to save the log settings to see why this is happening, it fails to save to every .ini file necessary to save it

https://user-images.githubusercontent.com/95429848/157349865-7a32a0f0-cbec-40ae-8201-b6ecf9417e25.mp4

Thank you for reading my Ted Talk

**Comment by Bankaimaster999** [comment]
This is Lumince's updated version of MMJR2 so please let him know about it so he can look into it. The last version I ever put out was 2.0-15993 before making the repo private.
Here is the link to the version you are using:
https://github.com/Lumince/Dolphin-MMJR2
