### ISSUE TITLE
I can't post issues on the MMJR2 Page of Luminces version nor do I have a proper way of communication between you or Lumince.

### ISSUE THREAD

**Issue by Vulcas** [Bankaimaster999/Dolphin-MMJR#33]
^^

**Comment by Bankaimaster999** [comment]
sadly I've taken a backseat to MMJR2 stuff however Lumince is on discord.
So unless you still on the last version I uploaded = 15993 

Then I shouldn't be the one you are reaching out to since I did update it past that version that was posted by me before.
