### ISSUE TITLE
Wii menu not starting up fully

### ISSUE THREAD

**Issue by Vulcas** [Bankaimaster999/Dolphin-MMJR#34]
Nothing changed, just went right in after installing the latest version and boom this happens:

https://user-images.githubusercontent.com/95429848/157435471-372a34fa-b6ff-4245-9a12-355768493465.mp4

What do I do?

**Comment by Bankaimaster999** [comment]
This is not an issue though ... since this version doesn't have the necessary code worked into it for the Wii menu yet.
I'll work on it later but that's not a priority for now.

**Comment by Vulcas** [comment]
I can't contact anyone working on the Lumince Version
