### ISSUE TITLE
Need Extra on Screen Button

### ISSUE THREAD

**Issue by blakbin** [Bankaimaster999/Dolphin-MMJR#36]
i just wondering if there is a chance to get extra button than can be binding to gamepad, especially a Classic Wii Gamepad Which is lack of L3 and R3 Button. On MMJ version when choosing a Clasic Gamepad, there is an extra Button 1 and Button 2.
it will be nice if the extra button can be modified to be use as combined button eg. press A & B at the same time

**Comment by Bankaimaster999** [comment]
This is not an issue ... please post these things in the discord
