### ISSUE TITLE
O jogo para na tela inicial

### ISSUE THREAD

**Issue by Exporta** [Bankaimaster999/Dolphin-MMJR#39]
Eu abaixei o aplicativo mas quando do início ao game o jogo para na tela inicial O jogo é resident Evil 4 gamecube ele fica parado na tela inicial de idioma já tentei configurar mais nada adianta

**Comment by Bankaimaster999** [comment]
wait for an update ... there was some issues with build 15951 and we are working on it. If the issue persists even after that repost the issue

**Comment by Exporta** [comment]
Ok 👍

Em dom., 20 de mar. de 2022 06:40, Bankaimaster999 ***@***.***>
escreveu:
