### ISSUE TITLE
Graphic bug in Vulkan in the game The Legend of Zelda - Twilight Princess

### ISSUE THREAD

**Issue by Realme5iuser** [Bankaimaster999/Dolphin-MMJR#4]
There is a graphic bug in the game The Legend of Zelda - Twilight Princess, smooth on Vulkan mode but the Map is black.

**Comment by TheOG00** [comment]
On sd665 run just fine

**Comment by Bankaimaster999** [comment]
I don't take issues here as there are more questions to ask ... like your settings and device, etc.
Those factors can also affect things on whichever backend you use. So please raise those issues in the discord and not here.
