### ISSUE TITLE
FPS decrease from 50 to 35 when add the 2nd player with dolphinbar

### ISSUE THREAD

**Issue by bobandyou** [Bankaimaster999/Dolphin-MMJR#41]
Two wii remote were connected by dolphinbar to play the game wii sport tennis.  FPS is 50 when only add one player. FPS is 35 when add two players. The setting of wii remote speaker is off.
Device: HUAWEI Mate20
CPU: Kirin 980
Game:  wii sport tennis

**Comment by Bankaimaster999** [comment]
More to emulate = Heavier emulation ....
not an issue

**Comment by bobandyou** [comment]
May be I did not say it clear. The 3D models of players in the game are always four, only the wii remote is added from 1 to 2.
