### ISSUE TITLE
"Wiimms Mario Kart Fun" Wii games aren't working on Dolphin MMJR 

### ISSUE THREAD

**Issue by ridwan47** [Bankaimaster999/Dolphin-MMJR#43]
None of the "Wiimms Mario Kart Fun" aren't working on Dolphin MMJR. 

They're working on Original play store Dolphin and also Dolphin MMJR2. 

But launching it on Dolphin MMJR crashes the whole app on startup. Which is such a shame because Dolphin MMJR has the best performance. 

Please fix it 🙏
Links can be found here
https://youtu.be/zCOnsQSr3EY

**Comment by Bankaimaster999** [comment]
Can't guarantee anything but I will keep note of it.

**Comment by ridwan47** [comment]
Thanks so much for considering 🥲
You can get the WBFS files from the description from these videos and also archive site listed below. 

https://youtu.be/zCOnsQSr3EY
https://youtu.be/gg2wyZunIf8
https://youtu.be/qj2JCLlQLyw
https://youtu.be/TWn5FOsRQXg
https://archive.org/details/rmce41

Thanks again 🙏🙂

**Comment by Joshy-2010** [comment]
I can confirm this exact problem.
