### ISSUE TITLE
Fatal frame 4 mask of lunar eclipse

### ISSUE THREAD

**Issue by Patrickz22** [Bankaimaster999/Dolphin-MMJR#43]
This game runs smoothly on dolphin mod, but with this mmjr it lags like hell, what should i do? Any good settings for this?

**Comment by Gamemulatorer** [comment]
Buy a new powerful phone and use dolphin emulator official beta

**Comment by Patrickz22** [comment]
I mean i can play it perfectly in dolphin mod, but here in mmjr its unplayble, or i need to do something to make it work properly but i dont know what to do, i already played with the settings and still lagging a lot, no luck.

**Comment by Patrickz22** [comment]
On top of that i already tried all or my games and it went really good except for this game, not sure whats really wrong with this game on mmjr.

**Comment by Bankaimaster999** [comment]
So you raised an issue to ask for better settings? If you cannot specify the issue then this is invalid and more so a complaint more than an issue ...
