### ISSUE TITLE
mayflash dolphinbar not working

### ISSUE THREAD

**Issue by Joshy-2010** [Bankaimaster999/Dolphin-MMJR#48]
Android 10, SD855, rooted, tested on versions v1.0-11500 & v1.0-11485

I already talked about this in discord I hope it's ok if I post it here, too.

I just bought a mayflash dolphinbar, and I got it working perfectly with dolphin mmjr2 running android 10 with an SD855. I enabled the appropriate settings such as continuous scanning and the setting under wii remotes, and after starting up a game android asked me if I want to **allow mmjr2 access to the usb device**. After allowing that, everything works great. But at least for my phone, this version of dolphin, mmjr, has much better performance. 

Unfortunately, if I repeat the same steps with this version, **I do not get the message asking me to allow usb access**. Instead, there's a yellow debug message from mmjr saying "wiimote 2 (wiimote 1 is my generic usb controller) disconnected". And unsurprisingly, the wiimote doesn't work. Maybe that's some new permission garbage in android 10 (that wasn't were in older android versions similliar to the sd card storage stuff) that is just not handled by mmjr and that's why the message asking me to allow access doesn't show up. Same behaviour in both versions mentioned above.

**Comment by Bankaimaster999** [comment]
MMJR2 and MMJR 1.0 are still on different code bases so comparing them in terms of features wouldn't get you anywhere (its like comparing the features of MMJR and Dolphin Official - and Official has way more features)

We can look into it but I can't guarantee anything
