### ISSUE TITLE
When I changed a game's settings the cheats is gone

### ISSUE THREAD

**Issue by elcoer** [Bankaimaster999/Dolphin-MMJR#49]
app version is Dolphin |MMJR| v1.0-11505.
game is The Legend of Zelda: Twilight Princess (GC)(JP)

**Comment by MaximusStreams** [comment]
This is happening on all games it seems, not just twighlight princess

**Comment by Bankaimaster999** [comment]
We are aware of the issue and are trying to work on it when we get the time to do so.
