### ISSUE TITLE
black screen with audio on zelda TP

### ISSUE THREAD

**Issue by nickarab** [Bankaimaster999/Dolphin-MMJR#5]
sometimes when I enter a new area or leave one, the area loading process never ends, the screen goes black and when I restart the emulator, the same problem repeats, I've tried to disable all hacks disable everything but it doesn't work, it doesn't always happen but when it does I have to uninstall and install the emulator again.

**Comment by Bankaimaster999** [comment]
I don't take issues here as there are more questions to ask ... like your settings and device, etc.
Those factors can also affect things on whichever backend you use. So please raise those issues in the discord and not here.
