### ISSUE TITLE
problem with android 12

### ISSUE THREAD

**Issue by YuckySoBae** [Bankaimaster999/Dolphin-MMJR#51]
problem with android 12, always crashing everytime i open any game

**Comment by SYKOV** [comment]
Qual versão está usando?

**Comment by SYKOV** [comment]
A versão 11500, está com travamentos aleatórios e falha nos controles( bug).

**Comment by Bankaimaster999** [comment]
I have a bunch of testers on android 12 and none reported that issue ....
So I will need more details on your device, the version of MMJR you using and how you installed it (update or clean install?)

**Comment by YuckySoBae** [comment]
Device: Vivo S1 Pro (Updated to android 12)
Version: MMJR v1.0-11505
Install: Clean install because update is no good

**Comment by YuckySoBae** [comment]
It's fine now. My bad! I'm sorry and thank you.. 🙏
