### ISSUE TITLE
Footer bar hides game icons of last row

### ISSUE THREAD

**Issue by mikelandzelo173** [Bankaimaster999/Dolphin-MMJR#54]
On the latest version with the revamped UI, it may happen that the footer bar (NGC | Wii | Ware) hides the last row of game icons if the content is big enough (or scrollable). There should be some padding at the bottom of the cover/icons grid to avoid this problem.

It may not be a problem if actual covers are shown but if the last row only consists of small icons they will be totally hidden by the footer bar.

**Comment by Gamer64ytb** [comment]
Can you send a screenshot to see better?

**Comment by mikelandzelo173** [comment]
![IMG_0238](https://user-images.githubusercontent.com/48515444/172110847-fb1fcbcc-d31f-4545-8113-be4f0ebbedfa.jpeg)

Sure. As you can see, in the last row there are two games listed but you can barely see them. However, you can navigate to them by using a controller (Ayn Odin) although there is no indicator of which game is selected. But that's another topic.

**Comment by Bankaimaster999** [comment]
Noted; we are looking into it
