### ISSUE TITLE
Running via Frontend: Save States not shown or loadable

### ISSUE THREAD

**Issue by regiimoep** [Bankaimaster999/Dolphin-MMJR#55]
Hello!

I am running MMJR from Pegasus (but Google tells me this is a problem that other Frontends have too) on an Ayn Odin.

When running any game from the MainActivity command the way Frontends do, you can access the save state menu and save states (even shown in the event log), but they are not shown in the menu. You can also not click the load button to load any of them.

Opening the Emulator standalone shows the States and they can be loaded then.

Is this a known issue or can be remedied in any way? Help would be appreciated!

I know we are a niche audience, but I thought it best to place as an issue anyway to see if this is already known.

**Comment by Bankaimaster999** [comment]
To aid in looking into this... Does Dolphin Official, MMJR2 or MMJ have this issue?

IF you can get me comparative feedback on that; maybe I can run it by the other half of the dev team to look into it if at least one of them has it already working properly?

**Comment by regiimoep** [comment]
I am not running MMJ or MMJR2 (I thought MMJR2 changes have been merged into MMJR by now?), but I can tell you that running the org.dolphinemu.dolphinemu variant (so the latest release from master over on the Dolphin Website) had a working Save State Menu also when opening via Pegasus. The Save States were reflected with their date and save time immediately and I could also load thenm.

**Comment by splitsurround** [comment]
I can confirm this is happening for me as well. I'm running the latest version of MMJR, on the Odin pro, using Launchbox as my frontend. Would love a fix!

**Comment by mjorgecardoso** [comment]
May I ask why “wontfix”? I understand it is low priority, but would you mind explaining your rationale?

**Comment by Bankaimaster999** [comment]
> May I ask why “wontfix”? I understand it is low priority, but would you mind explaining your rationale?

ANNOUNCEMENT (which is on the Front page of this repo):

=============================

I officially announce that I will be stopping any further development on BOTH projects and calling it quits to focus on University. Sorry to everyone that held in here for further development on |MMJR2| and for possible fixes down the line for |MMJR| .... but it really is too much for me to handle right now.

Both versions are on github and I encourage determined or curious people to use the source code. However at the rate that Dolphin Official is going, down the line you might not need |MMJR| or definitely not |MMJR2| anymore. I might have time to push any PR's over to Dolphin Official from |MMJR2| for QOL stuff like the theme changer or maybe the quick menu but like I said everything is on github and free to access so anyone can do it if in case I can't. As for whether I will come back and tackle this project again ... I have no clue; I might still try to work on it little by little over time but as it stands I'm officially too tied down with IRL stuff to handle the projects anymore.

So special thanks to @Lynx for his godly help and contributions and the testers; especially @Gamer 64 for his assistance over the recent months. As well as to @Jos for the great updates, knowledge and development over at Dolphin Official (https://dolphin-emu.org/download/). Thanks to everyone for supporting the app, development and my endeavors in learning coding from scratch.

=================================
