### ISSUE TITLE
Changing discs crashes the current game

### ISSUE THREAD

**Issue by tony-rockets** [Bankaimaster999/Dolphin-MMJR#57]
Tested with Tiger Woods PGA 2004 (European version) on latest build with AYN Odin (SD 845). When the game asks for the second disc to be inserted, using the 'Change Disc' option in the header menu allows you to navigate and select the second disc, and when the game attempts to read the disc you are thrown back to the MMJR game library. This also happens if you enable 'Change Discs Automatically' in your settings - I can confirm that the both disc images are good, either can be booted and go in-game when loaded (both on native hardware and in Dolphin), it's only when you attempt to change discs and the emu begins reading the second disc that this occurs.

**Comment by Gamer64ytb** [comment]
Known issue, that's related with scoped storage changes we made. We needed remove a part of scoped storage beacuse was giving compilation issues, and we don't know why, and that affected to change disc option, we will try found a solution. The affected code: https://github.com/Bankaimaster999/Dolphin-MMJR/blob/5c4c7056765a52a4ddc60637fa8f4c004d705e55/Source/Core/Common/FileUtil.h#L221.
