### ISSUE TITLE
Major Graphical Issues in Sonic Heroes

### ISSUE THREAD

**Issue by chrisasma103** [Bankaimaster999/Dolphin-MMJR#58]
Hi, I recently tried to play Sonic Heroes, and it was all fine until the first level started. Here is an image which shows the lighting issue: https://imgur.com/BYqNX2K. Apparently, this used to happen in Dolphin Official as well, and it is discussed on Sonic Heroes' Dolphin Wikia page: https://wiki.dolphin-emu.org/index.php?title=Sonic_Heroes#Graphical_Glitches_with_IR.3E1. Hopefully, the solution there can be ported to MMJR. Thanks for all your hard work!

**Comment by Bankaimaster999** [comment]
I think this would need the importation of vertex rounding .... not sure if I or gamer64 will have the time to look into it though but we will keep this in mind.

**Comment by Gamer64ytb** [comment]
Unfortunately that's normal on MMJ versions, beacuse for some reason Vertex Rounding don't work. No idea what is causing that, but maybe you can help to found it. Can you try with first dolphin MMJ version and let me know if that get fixed or not? (The first MMJ version is 5.0-8937)

**Comment by chrisasma103** [comment]
I loaded the game up on the first MMJ and it seemed to work: https://imgur.com/tJLSdX7

**Comment by Alimaster1999** [comment]
Will this emulator be updated or has it stopped working please reply

**Comment by Bankaimaster999** [comment]
> I loaded the game up on the first MMJ and it seemed to work: https://imgur.com/tJLSdX7

Which version of MMJ are you using here?

**Comment by chrisasma103** [comment]
> > I loaded the game up on the first MMJ and it seemed to work: https://imgur.com/tJLSdX7
> 
> Which version of MMJ are you using here?

The one I was told to use. Version 5.0-8937. This one: https://github.com/weihuoya/dolphin/releases/tag/Dolphin_5.0-8937

**Comment by chrisasma103** [comment]
Sorry, I just realized that when I tested this, I didn't change the resolution, which was the whole point. On the first Dolphin MMJ, if you change the resolution, the textures freak out in the same way. Here's proof: https://imgur.com/xIr7LoR
