### ISSUE TITLE
Controller profiles

### ISSUE THREAD

**Issue by Vicv07** [Bankaimaster999/Dolphin-MMJR#64]
Is there a way to add controller profiles? I have a handheld and every time I want to use a Bluetooth controller instead of the built in controls, I have to remap the controller port. Would be awesome to just switch between them. Also having a quit option in the in game settings as the only way I know is to swipe back a couple times which doesn’t work with a controller. Otherwise this is an awesome program and runs my games very well/lots of options. Thank you

**Comment by Bankaimaster999** [comment]
Honestly I don't believe there is a system like that in place for this build or MMJR2; however, even if we did know how to go about adding it in ... I am no longer working on the builds nor does it seem like the other dev assisting me is. Therefore I advise using the original and official Dolphin Emulator as they are constantly working on that build.

**Comment by Vicv07** [comment]
No problem thanks for getting back to me. It’s not that big of a deal just a nice feature. Only takes a couple minutes to get it set up each time. I don’t imagine normal dolphin would work very well on my handheld though
