### ISSUE TITLE
internal audio recording permission

### ISSUE THREAD

**Issue by M-hyun** [Bankaimaster999/Dolphin-MMJR#65]
i tried many third-party recording app's
the internal audio recording does work with official dolphin/aethersx2/skyline/citra mmj
( and they appears in the supported list too)
but it doesn't in dolphin mmjr as the video shows

https://user-images.githubusercontent.com/117160684/217170168-84dad8ca-f5bb-42ce-84c7-dd351d1bac0c.mp4

**Comment by Bankaimaster999** [comment]
Please refer to the Announcement, at the bottom, in the README.md on the code page:
https://github.com/Bankaimaster999/Dolphin-MMJR
