### ISSUE TITLE
Please Fix, no internal sound when recording screen

### ISSUE THREAD

**Issue by rahmadaidillahr0312** [Bankaimaster999/Dolphin-MMJR#7]
When I record the internal sound screen, the recording does not have the internal sound, hopefully it can be fixed to give the application access for internal sound

**Comment by Bankaimaster999** [comment]
The app doesn't need permissions to record internal sound that is for the recorder; this is also evident with the countless Youtube videos showing that it records internal sound just fine with the recorders that have those permissions. I have also tested to confirm everything is working fine as well.

You have to remember the app doesn't have any function to record sound, the most it can do is take a screenshot, HOWEVER, there are certain screen recorders (some built-in or third party) that do not internally record sound for apps or in general. Those usually require permissions for that are at Super User Levels (aka Rooting the device for super user privileges). End point is its your screen recorder that needs permissions to record internal sound and not the emulator itself; therefore its not an Emulator issue but a phone/recorder issue.

**Comment by simonjonnemeth** [comment]
> The app doesn't need permissions to record internal sound that is for the recorder; this is also evident with the countless Youtube videos showing that people are able to record internal sound just fine with the recorders that have those permissions. I have also tested to confirm everything is working fine as well.
> 
> You have to remember the app doesn't have any function to record sound, the most it can do is take a screenshot, HOWEVER, there are certain screen recorders (some built-in or third party) that do not internally record sound for apps or in general. Those usually require permissions for that at Super User Level (aka Rooting the device for super user privileges). End point is its your screen recorder that needs permissions to record internal sound and not the emulator itself; therefore its not an Emulator issue but a phone/recorder issue.

This is not true. You need to learn how Android works since Android 10. Developers need to allow it in their apps for us to record internal sound via screen capture softwares. Samsung devices are the only ones that can do it without and only using Samsung's own screen capture software. Being rooted no longer has anything to do with this.
